# These are supported funding model platforms

github: hunterhogan
patreon: integrated
open_collective: # Replace with a single Open Collective username
ko_fi: hunterhogan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: HunterHogan
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
buy_me_a_coffee: hunterhogan
thanks_dev: u/gh/hunterhogan
custom: ['https://www.paypal.me/hunterhogan', 'https://hunterthinks.com/support'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
