extend = "pyproject.toml"

line-length = 140

[lint]
preview = true
allowed-confusables = [
  "–",
  "′",
  "×",
  "−",
  "∨",
  "∪",
  "⊗",
  "𝔼",
  "ℱ",
  "𝕀",
  "ℓ",
  "ℒ",
  "ℕ",
  "ℝ",
  "𝒮",
  "α",
  "Β",
  "γ",
  "ρ",
  "σ",
]
ignore = [
  "any-type",
  "complex-structure",
  "missing-trailing-comma",
  "incorrect-blank-line-after-class",
  "docstring-tab-indentation",
  "missing-trailing-period",
  "non-imperative-mood",
  "line-too-long",
  "unused-import",
  "FIX",
  "static-join-to-f-string",
  "I",
  "N",
  "blanket-noqa",
  "type-name-incorrect-variance",
  "dict-index-missing-items",
  "useless-import-alias",
  "non-ascii-name",
  "non-ascii-import-name",
  "too-many-branches",
  "too-many-arguments",
  "too-many-statements",
  "too-many-nested-blocks",
  "magic-value-comparison",
  "useless-else-on-loop",
  "redefined-loop-name",
  "typed-argument-default-in-stub",
  "docstring-in-stub",
  "redundant-numeric-union",
  "snake-case-type-alias",
  "bad-quotes-inline-string",
  "superfluous-else-return",
  "superfluous-else-continue",
  "explicit-f-string-type-conversion",
  "subprocess-without-shell-equals-true",
  "if-else-block-instead-of-if-exp",
  "yoda-conditions",
  "TD",
  "tab-indentation",
  "missing-newline-at-end-of-file",
  "missing-copyright-notice",
  "incorrect-section-order",
  "no-space-after-block-comment",
  "blank-lines-top-level",
  "too-many-blank-lines",
  "blank-lines-after-function-or-class",
  "too-many-locals",
  "too-many-positional-arguments",
  "suspicious-pickle-import",
]
select = ["ALL"]
task-tags = ["DEVELOPMENT", "FailEarly", "NOTE", "SEMIOTICS", "TODO"]

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-import-conventions]
banned-aliases = { numpy = ["np"], pandas = ["pd"], regex = ["re"] }

[lint.flake8-import-conventions.aliases]
"accelerate.utils.dataclasses" = "accelerate_dataclasses"
"fs.path" = "fs_path"
"itertools.product" = "CartesianProduct"
"torch.autograd.grad" = "torch_grad"
"torch.nn.functional" = "F"
"torch.nn.parallel.DistributedDataParallel" = "DDP"
numpy = "numpy"
pandas = "pandas"
re = "regex"

[lint.flake8-quotes]
inline-quotes = "single"

[lint.per-file-ignores]
"__init__.py" = ["useless-import-alias"]
"*test*.py" = [
  "ARG",
  "BLE",
  "D",
  "DTZ",
  "FBT",
  "PT",
  "assert",
  "suspicious-non-cryptographic-random-usage",
  "TRY",
  "docstring-missing-returns",
]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
quote-style = "single"
indent-style = "tab"
skip-magic-trailing-comma = true
