extend = "pyproject.toml"

line-length = 140

[lint]
preview = true
allowed-confusables = [
  "–",
  "′",
  "×",
  "−",
  "∨",
  "∪",
  "⊗",
  "𝔼",
  "ℱ",
  "𝕀",
  "ℓ",
  "ℒ",
  "ℕ",
  "ℝ",
  "𝒮",
  "α",
  "Β",
  "γ",
  "ρ",
  "σ",
]
ignore = [
  "ANN401",
  "C901",
  "COM812",
  "D204",
  "D206",
  "D400",
  "D401",
  "E501",
  "F401",
  "FIX",
  "FLY002",
  "I",
  "N",
  "PGH004",
  "PLC0105",
  "PLC0206",
  "PLC0414",
  "PLC2401",
  "PLC2403",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "PLR1702",
  "PLR2004",
  "PLW0120",
  "PLW2901",
  "PYI011",
  "PYI021",
  "PYI041",
  "PYI042",
  "Q000",
  "RET505",
  "RET507",
  "RUF010",
  "S603",
  "SIM108",
  "SIM300",
  "TD",
  "W191",
  "W292",
  "CPY001",
  "D420",
  "E265",
  "E302",
  "E303",
  "E305",
  "PLR0914",
  "PLR0917",
  "S403",
]
select = ["ALL"]
task-tags = ["DEVELOPMENT", "FailEarly", "NOTE", "SEMIOTICS", "TODO"]

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-import-conventions]
banned-aliases = { numpy = ["np"], pandas = ["pd"], regex = ["re"] }

[lint.flake8-import-conventions.aliases]
"accelerate.utils.dataclasses" = "accelerate_dataclasses"
"fs.path" = "fs_path"
"itertools.product" = "CartesianProduct"
"torch.autograd.grad" = "torch_grad"
"torch.nn.functional" = "F"
"torch.nn.parallel.DistributedDataParallel" = "DDP"
numpy = "numpy"
pandas = "pandas"
re = "regex"

[lint.flake8-quotes]
inline-quotes = "single"

[lint.per-file-ignores]
"__init__.py" = ["PLC0414"]
"test*.py" = [
  "ARG",
  "BLE",
  "D",
  "DTZ",
  "FBT",
  "PT",
  "S101",
  "TRY",
  "DOC201",
]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
quote-style = "single"
indent-style = "tab"
skip-magic-trailing-comma = true
