name: Python Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:

  get-project-info:
    runs-on: ubuntu-latest
    outputs:
      tests-python-versions: ${{ steps.get-project-info.outputs.versions }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'

      - name: Cache, pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-a-dee-doo-dah
          restore-keys: pip-a-dee-doo-dah

      - run: pip install packaging requests

      - id: get-project-info
        run: |
          python -c "
          import itertools, json, os, packaging.specifiers, packaging.version, pathlib, requests, tomllib

          dictionaryProject = tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']

          listPythonVersions = [str(max(group))
            for _key, group in itertools.groupby(
              packaging.specifiers.SpecifierSet(dictionaryProject['requires-python']).filter(
                packaging.version.Version(manifest['version'])
              for manifest in requests.get(
                'https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json'
                ).json())
              , lambda V: V.release[0:-1])]

          with open(os.environ['GITHUB_OUTPUT'], 'a') as writeStream:
            writeStream.write(f'versions={json.dumps(listPythonVersions)}\n')
          "

  make-testbeds:
    needs: get-project-info
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests-python-versions: ${{ fromJson(needs.get-project-info.outputs.tests-python-versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache, pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-a-dee-doo-dah
          restore-keys: pip-a-dee-doo-dah

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tests-python-versions }}

      - run: pip install ".[testing]"
      - run: pytest
