name: Update CITATION.cff

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

defaults:
  run:
    shell: bash

jobs:
  updateCitation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.11"

      - name: Cache, pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-a-dee-doo-dah
          restore-keys: pip-a-dee-doo-dah

      - name: Install and run updateCitation
        run: |
          set -e
          pip install updateCitation
          python -c "import updateCitation; updateCitation.here()"
